---
name: "Build RTG Gatsby Site"

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm

    - name: Build Site
      run: npm build

    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.5
        tf_actions_subcommand: 'init'

    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.5
        tf_actions_subcommand: 'plan'

    - name: 'Terraform Apply'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.5
        tf_actions_subcommand: 'apply --auto-apply'

    - uses: jsidberry/action-aws-cli@v1.1
    - name: sync to s3
      run: aws s3 sync public s3://rtg.com
